title: SeongHyeon
lang: en
description: SeongHyeonP GitHub Pages

## remote method ##
#remote_theme: rundocs/jekyll-rtd-theme

theme: null

#debug:
#  compress: false
#  dist: true
#  shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
#  - jekyll-coffeescript
#  - jekyll-default-layout
#  - jekyll-gist
#  - jekyll-github-metadata
#  - jekyll-optional-front-matter
#  - jekyll-paginate
#  - jekyll-readme-index
#  - jekyll-titles-from-headings
#  - jekyll-relative-links

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec

github: [metadata]
