title: SeongHyeonP.github.io
lang: en
description: SeongHyeonP GitHub Pages

## remote method ##
remote_theme: rundocs/jekyll-rtd-theme

#debug:
#   compress: false
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
